### ISSUE TITLE
[DOC] Constraints and Qualities

### ISSUE THREAD

**Issue by anitahaurie** [t-vaudry/project_emu#10]
Section 2.3

"This section describes applicable quality standards and non-functional requirements that the system shall meet, like: performance, usability, reliability, interoperability, scalability, security, etc.
Include any design constraints, external constraints or other dependencies, hardware or platform requirements.
Constraints and qualities should be described in concrete terms.  Where possible, metrics should be applied."

**Comment by puthrichard** [comment]
shotgun
