### ISSUE TITLE
[DOC] Technical Resources

### ISSUE THREAD

**Issue by anitahaurie** [t-vaudry/project_emu#13]
Section 3.2

"Present here the computer resources available for the project. That includes computers, software resources (tools, libraries, etc.) available on these computers"

**Comment by anitahaurie** [comment]
Not assigning anyone on the doc team here, since I think it's a relatively small task. Someone from coding can just write up a few sentences describing the computer resources available.

**Comment by Persepolis1** [comment]
will take it

**Comment by Persepolis1** [comment]
Available for review
