### ISSUE TITLE
[DOC] Scoping

### ISSUE THREAD

**Issue by anitahaurie** [t-vaudry/project_emu#14]
Section 4.

"With regard to the cost/time necessary to meet all the goal presented in section 3, and given the resources  available presented in section 4, give here the scope of the solution that you will implement in the project.
List all features/goals/qualities that will be left out because of lack of time/resources."

**Comment by Rick--D** [comment]
Ready for revision on Outlook -- feedback is welcome.

**Comment by Rick--D** [comment]
Revision v2.0 done -- new and improved with fancy headers!
