### ISSUE TITLE
[DOC] Activities

### ISSUE THREAD

**Issue by anitahaurie** [t-vaudry/project_emu#19]
Section 6.1

"Describe what are the main activities involved in your project. An activity is something that must be undertaken in order to produce an artifact that is useful in reaching the goals of the project. Each activity shall have a clear purpose, and shall yield at least one artifact as an output."

**Comment by anitahaurie** [comment]
This one depends on the artifacts, which I assigned myself to. I'll have my first pass of the artifacts done by this weekend so you can start work on this.

**Comment by salaman** [comment]
Here's some of the steps that have to be done coding-side which I immediately see, however I'm sure this will evolve once more progress is made:

1. Development environment setup (1w)
	1. Production server setup (2d)
		2. Software installation
		3. User creation
		4. Database creation
	2. Travis CI setup (3d)
		1. Generate deployment keys
		2. Build scripts
	3. Personal workstation setup (2d)
2. Install and configure Laravel framework (1d)
3. Database pre-requisites (1w)
	1. Translate domain model objects into data objects (1d)
	2. Insert course/section data into database (2d)
	3. Fill out pre-requisites for courses (2d)
	4. Generate mock student accounts and records (2d)
4. Student authentication (2d)
	1. Login (1d)
	2. Registration (1d)
5. Module - Student account (1w)
	1. Create pages for student preference management
	2. Create pages for student record management
6. Module - Sequence generator (2w)
7. Module - Schedule generator (2w, parallel with 6)
8. Integrate both generators into UI (1w)
9. UI design work (1w, parallel with project)

If you want, the server (step 1), database (step 3) and modules (steps 5, 6, 7) can be artifacts.

I'll open an issue per main step so the coding team can self-assign once people proofread this and make sure I'm not forgetting anything.
