### ISSUE TITLE
[DOC] Project Estimates

### ISSUE THREAD

**Issue by anitahaurie** [t-vaudry/project_emu#21]
Section 6.3

"Provide a realistic estimated cost and schedule for the project, as well as the basis for those estimates, and the points and circumstances in the project when re-estimation might occur. 
Evaluate the cost of production of each artifact, as described in the previous section, and then adding up the numbers."

**Comment by anitahaurie** [comment]
This one seems kinda funky given that we're not spending any money on this project and that there already is a section called "Schedule". I suggest looking at past projects to see how they approached this.

**Comment by Shmeve** [comment]
I get the feeling they expect us to come up with some costs, as if we were being paid for our work. This is from one of the provided samples:

![Image](http://puu.sh/mxZIP/1cfff1b309.png)

So I guess certain features/artifacts need to be given a monetary value depending on how long they take to implement and how many people are required for the task.

**Comment by anitahaurie** [comment]
You seemed knowledgeable, so I assigned you :) I assigned myself the artifacts, so you'll kinda have to wait on that before being able to finish this. I'll try to have a first draft of the artifacts done by this weekend so you can start working on this.

**Comment by Shmeve** [comment]
Sounds good. We have plenty of time so just let me know when we have a rough draft and I'll get started.

**Comment by salaman** [comment]
Weirdly enough, the "cost" in @Shmeve's example above is in hours, not currency. If that's allowable, it's likely easier than thinking of monetary values.

**Comment by Shmeve** [comment]
True. It's really weird but I assume there will be an explanation at some point in class or the tutorial giving more details. Either way it will probably make more sense once the schedule is done.

**Comment by anitahaurie** [comment]
I believe past examples use hours as well, so it shouldn't be a problem.

**Comment by dsecca** [comment]
@t-vaudry has experience with Activity-on-node which can play nicely with this issue. He will now be assigned to this issue.

**Comment by t-vaudry** [comment]
WIP

**Comment by t-vaudry** [comment]
Section complete.
Activity on node diagram added. Test print done to see if legible.
Ready for review.
