### ISSUE TITLE
[DOC] Activities Assignments

### ISSUE THREAD

**Issue by anitahaurie** [t-vaudry/project_emu#22]
Section 6.4

"Assign the different activities to your team members, according to their capacities and schedule limitations, as presented in section 4.1."

**Comment by dsecca** [comment]
@anitahaurie I finished the Activities Assignments based on what I know from the doc team and from what Chris and others told me from the coding team. I'm closing this issue.

**Comment by t-vaudry** [comment]
Need final review of David's new additions once complete

**Comment by dsecca** [comment]
@anitahaurie @t-vaudry @Shmeve @daniel-adams I finished and reviewed this section in the document. It's ready for a final review before this issue can be closed. Thanks!
