### ISSUE TITLE
[DOC] Schedule

### ISSUE THREAD

**Issue by anitahaurie** [t-vaudry/project_emu#23]
Section 5.5

"Diagrams or tables showing target dates for completion of iterations and phases, release points, demos, and other milestones, e.g. a Gantt chart. "

**Comment by Shmeve** [comment]
Here is a sample time schedule from an assignment @salaman and I did in CEGEP. Looking at some of the samples it appears to be exactly what they are expecting (Gnatt Chart). 

![image](https://cloud.githubusercontent.com/assets/10710596/12373364/c1e45ca6-bc44-11e5-99e9-e54087a9714d.png)

**Comment by anitahaurie** [comment]
thanks @Shmeve . Did you use a particular software to generate that chart? Maybe we can assign @dsecca to this one as lead? We can make a first pass at it and then have everyone review it to make sure it's realistic.

**Comment by Shmeve** [comment]
@dsecca I asked my friend who made the schedule for that project, he said it was done in Visio. Unfortunately he doesn't have a copy of the Visio file anymore so I'll see if I can find a template for Visio in a bit.

**Comment by salaman** [comment]
@anitahaurie The chart is just using the regular built-in "Gantt Chart" template in Visio. It draws the bars automatically, which is nice.

**Comment by dsecca** [comment]
@Shmeve I'll use the built-in Gantt Chart Anita is talking about. @anitahaurie  I'll work on it and have done by Wednesday and then we can, as you suggested, look it over as a group to make sure we have enough time for everything.

**Comment by dsecca** [comment]
@anitahaurie @salaman Here's a pdf of a Gantt chart with the tasks we've come up with so far (The snapshot tool isn't working for some reason so I had to make a pdf...). Some of the coding tasks have already been completed by Chris so I tried to realistically place them in the time frame he gave me. Although testing is ongoing throughout this project, I made some "Final Testing" slots in case something goes wrong and we need to buy more time. Let me know what you think!

[SOENSchedule.pdf](https://github.com/t-vaudry/project_emu/files/99256/SOENSchedule.pdf)

**Comment by dsecca** [comment]
I posted the Gantt Chart in the Deliverable file on Outlook. All I have left is to write a little blurb before the picture.

**Comment by t-vaudry** [comment]
review pending new gantt chart

**Comment by dsecca** [comment]
New Gantt chart is posted with deliverable activities and changed appearance. Please take a look at it before the ticket can be closed. Thanks!

**Comment by anitahaurie** [comment]
Trusting that all activities were included. I won't bother double-checking the duration of everything but I assume it's consistent with what's written in the project estimates.
