### ISSUE TITLE
[DOC] Prototyping

### ISSUE THREAD

**Issue by anitahaurie** [t-vaudry/project_emu#25]
Section 7.

"Describe any work undertaken in development of a prototype.  A prototype should be developed during this phase both to prove the technologies used are appropriate to the task and to assess the competence of the team to work with the selected technologies."

**Comment by anitahaurie** [comment]
@salaman I'm leaving this one assigned to you since it's the description of the prototype to be developed in code. This could probably just be a brief description of the code completed by the time this deliverable is due.

**Comment by salaman** [comment]
Available for proofreading. Docs team can close the issue if no problems are found.
