### ISSUE TITLE
[DOC] Functional Requirements: Use Case Diagram

### ISSUE THREAD

**Issue by anitahaurie** [t-vaudry/project_emu#31]
Part of Functional Requirements

Section 2.1

"This section should describe the requirements that the software shall have. It should define the fundamental actions that must take place in the software in accepting and processing the inputs and in processing and generating the outputs. 
The overall functional requirements shall be presented graphically as a use case model.

Each individual requirement shall be presented as a use case. Also, each requirement should be rated in terms of difficulty and importance in order to provide useful discrimination factors for the project scoping presented in section 5. "

**Comment by salaman** [comment]
### Login page

- Log in
- Log out
- (Anonymous actor:) Register account

### Profile page

- (Modify profile information)
- (Delete account)
- View completed courses
- Add completed course
- Remove completed course
- Modify schedule preferences
- Modify sequence preferences

### Sequence-related

- Select electives
- Generate sequence

### Schedule-related

- Generate schedule (for term)
- (Regenerate schedule)

I'll get started on writing these once I get approval.

**Comment by Shmeve** [comment]
Added use case diagram based off of @salaman's suggestions.

**Comment by salaman** [comment]
Available for final review.
