### ISSUE TITLE
[DOC] Functional Requirements: Use Case Description

### ISSUE THREAD

**Issue by anitahaurie** [t-vaudry/project_emu#32]
Description of every use case based on Steve's diagram

Section 2.1

"This section should describe the requirements that the software shall have. It should define the fundamental actions that must take place in the software in accepting and processing the inputs and in processing and generating the outputs. 
The overall functional requirements shall be presented graphically as a use case model.

Each individual requirement shall be presented as a use case. Also, each requirement should be rated in terms of difficulty and importance in order to provide useful discrimination factors for the project scoping presented in section 5. "

**Comment by Shmeve** [comment]
Added use case description template to the word document (2.1.3). For each use case please proved a brief in section 2.1.2. Just a small simple explanation of what the use case does. These briefs will be summarized further in the description.

**Comment by salaman** [comment]
Needs some touch-ups after the TA's input, will close once complete and notify @Shmeve so he can update the diagram.

**Comment by salaman** [comment]
Available for final review.
