### ISSUE TITLE
[DOC] Project Description

### ISSUE THREAD

**Issue by anitahaurie** [t-vaudry/project_emu#6]
Point 2 of deliverable 1. Not too much info given here, so I suggest looking at past projects for inspiration.

**Comment by anitahaurie** [comment]
I believe this corresponds to the "system overview" written for deliverable 0. We can probably use it exactly as is.

**Comment by Rick--D** [comment]
The deliverable 0 Word document says "the above nformation(sic) will become part of your Deliverable 1" so yeah, we basically just have to expand on what we've already done.

**Comment by anitahaurie** [comment]
Seeing as we got "excellent" for deliverable 0, I conclude that no more work needs to be done for this section.
