### ISSUE TITLE
[DOC] Goals and Constraints

### ISSUE THREAD

**Issue by anitahaurie** [t-vaudry/project_emu#7]
Section 3. of deliverable 1

"Goals and Constraints [A brief description of the purpose and objectives of this project and a brief description of what deliverables the project is expected to deliver. length: 1/2 - 1 page

This section aims at describing all the goals of the project in terms of features and qualities to be implemented, as well as constraints imposed on the solution. 
Note that this section is to present all expected features, which can then later be eventually scoped down in section 5, given the resource limitations exposed in section 4. 
Discrimination factors such as relative importance and difficulty are to be provided in order to proceed with the scoping.. "

**Comment by t-vaudry** [comment]
Issue will be closed pending review.
