### ISSUE TITLE
[DOC] Functional Requirements

### ISSUE THREAD

**Issue by anitahaurie** [t-vaudry/project_emu#8]
Section 2.1

"This section should describe the requirements that the software shall have. It should define the fundamental actions that must take place in the software in accepting and processing the inputs and in processing and generating the outputs. 
The overall functional requirements shall be presented graphically as a use case model.  
Each individual requirement shall be presented as a use case.  Also, each requirement should be rated in terms of difficulty and importance in order to provide useful discrimination factors for the project scoping presented in section 5.  "

**Comment by anitahaurie** [comment]
Now split up into two sub-issues:
Use Case Diagram
Use Case Description

**Comment by salaman** [comment]
Closed, covered by #31 and #32.
