### ISSUE TITLE
[DOC] Domain Model for deliverable 1

### ISSUE THREAD

**Issue by anitahaurie** [t-vaudry/project_emu#9]
Section 3.2

Exactly as in deliverable 0. Creating issue for consistency.

"This is a diagram consisting of domain level objects and their attributes and associations. Include an explanation of the model commenting on each component and its relationship to the other components."

**Comment by Shmeve** [comment]
I will remake the diagram using StarUML and make the recommended changes.

**Comment by Shmeve** [comment]
v1 of the diagram is on drive in the Deliverable1 folder.

**Comment by Shmeve** [comment]
Reopening this because I still need to touch up the descriptions to match the new model.

**Comment by Shmeve** [comment]
2.2.2 Domain Model Description updated to match new diagram.
